"""
nodes/assembler_node.py — LangGraph Node 5

Takes the dict of TSX components produced by coder_node and:
  1. Verifies all sections were generated and are valid (fix #3)
  2. Scaffolds a minimal Next.js 14 (App Router) project structure
  3. Writes each component to app/components/<Name>.tsx
  4. Generates app/page.tsx that imports and renders all components in order
  5. Generates app/globals.css from global_css + any inline @font-face rules
  6. Copies all downloaded assets to public/assets/
  7. Writes package.json, tsconfig.json, next.config.js

Fixes applied:
  - Issue #3: completeness check — aborts if any section is missing/invalid
  - Issue #5: returns absolute nextjs_output_dir reliably
  - Issue #7: asset paths rewritten ./assets/ → /assets/ for Next.js public/
  - Issue #8: validates every TSX before writing

Output dir: nextjs-output/   (sibling to cloned-site/)
"""

import os
import re
import shutil
from pathlib import Path

from state import ClonerState
from nodes.validation import validate_tsx, validate_components, verify_page_imports


# ─────────────────────────────────────────────────────────────────────────────
# CONFIG
# ─────────────────────────────────────────────────────────────────────────────

CLONED_SITE_DIR  = "cloned-site"
ASSETS_SRC       = os.path.join(CLONED_SITE_DIR, "assets")
NEXTJS_DIR       = "nextjs-output"


# ─────────────────────────────────────────────────────────────────────────────
# SCAFFOLD TEMPLATES
# ─────────────────────────────────────────────────────────────────────────────

PACKAGE_JSON = """\
{
  "name": "cloned-site",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev":   "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next":    "14.2.3",
    "react":   "^18",
    "react-dom": "^18"
  },
  "devDependencies": {
    "@types/node":       "^20",
    "@types/react":      "^18",
    "@types/react-dom":  "^18",
    "typescript":        "^5"
  }
}
"""

TSCONFIG_JSON = """\
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
"""

NEXT_CONFIG = """\
/** @type {import('next').NextConfig} */
const nextConfig = {};
module.exports = nextConfig;
"""

LAYOUT_TSX = """\
import type {{ Metadata }} from 'next';
import './globals.css';

export const metadata: Metadata = {{
  title: '{title}',
}};

export default function RootLayout({{
  children,
}}: {{
  children: React.ReactNode;
}}) {{
  return (
    <html lang="en">
      <body>{{children}}</body>
    </html>
  );
}}
"""

README_MD = """\
# Cloned Site — Next.js Output

Generated by Webpage Cloner (LangGraph + DeepSeek).

## Getting started

```bash
npm install
npm run dev
```

Then open http://localhost:3000

## Structure

```
app/
  page.tsx          ← root page (imports all sections)
  layout.tsx        ← root layout
  globals.css       ← global fonts, variables, resets
  components/       ← one TSX file per section
public/
  assets/           ← all downloaded images, fonts, icons
```
"""


# ─────────────────────────────────────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────────────────────────────────────

def _component_name(section_name: str) -> str:
    """'hero_2' → 'Hero2',  'call-to-action' → 'CallToAction'"""
    parts = re.split(r"[-_]", section_name)
    return "".join(p.capitalize() for p in parts if p)


def _fix_asset_paths(tsx: str) -> str:
    """
    Rewrite asset paths so Next.js resolves them from public/.

    Covers:
      ./assets/     → /assets/
      /images/      → /assets/images/     (bare /images/ invented by model)
      ./images/     → /assets/images/
      /videos/      → /assets/videos/
      /posters/     → /assets/posters/
    """
    # ./assets/ → /assets/
    tsx = tsx.replace("./assets/", "/assets/")

    # bare /images/, /videos/, /posters/ without /assets/ prefix
    tsx = re.sub(r'(?<!/assets)(/images/)', r'/assets\1', tsx)
    tsx = re.sub(r'(?<!/assets)(/videos/)', r'/assets\1', tsx)
    tsx = re.sub(r'(?<!/assets)(/posters/)', r'/assets\1', tsx)

    # ./images/, ./videos/, ./posters/ (relative without assets/)
    tsx = tsx.replace("./images/",  "/assets/images/")
    tsx = tsx.replace("./videos/",  "/assets/videos/")
    tsx = tsx.replace("./posters/", "/assets/posters/")

    return tsx


def _write(path: str, content: str):
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


# ─────────────────────────────────────────────────────────────────────────────
# PAGE.TSX GENERATOR
# ─────────────────────────────────────────────────────────────────────────────

def _build_page_tsx(section_names: list[str]) -> str:
    imports = []
    usages  = []

    for name in section_names:
        cname = _component_name(name)
        imports.append(f"import {cname} from './components/{cname}';")
        usages.append(f"      <{cname} />")

    imports_str = "\n".join(imports)
    usages_str  = "\n".join(usages)

    return f"""\
import React from 'react';
{imports_str}

export default function Page() {{
  return (
    <main>
{usages_str}
    </main>
  );
}}
"""


# ─────────────────────────────────────────────────────────────────────────────
# MAIN NODE
# ─────────────────────────────────────────────────────────────────────────────

def assembler_node(state: ClonerState) -> dict:
    try:
        components    = state.get("components", {})
        global_css    = state.get("global_css", "")
        page_title    = state.get("page_title", "Cloned Page")
        sections      = state.get("sections", [])
        failed_sects  = state.get("failed_sections", [])

        if not components:
            return {
                "error": "assembler_node: no components in state",
                "logs":  ["Assembler failed: no components"],
            }

        # ── Issue #3: Completeness + validity check ───────────────────────
        print("\n🔍 Assembler: verifying component completeness …")

        valid_names, invalid_names = validate_components(sections, components)

        if invalid_names:
            # Some sections are outright missing or invalid — abort so builder
            # never runs with broken output.
            msg = (
                f"assembler_node: {len(invalid_names)} section(s) missing or invalid: "
                f"{invalid_names}. "
                f"Aborting assembly — re-run coder for these sections."
            )
            print(f"  ❌ {msg}")
            return {
                "error": msg,
                "logs":  [msg],
            }

        # Warn about sections that failed in coder but didn't make it here
        if failed_sects:
            print(
                f"  ⚠️  {len(failed_sects)} section(s) permanently failed in coder "
                f"and will be absent from the page: {failed_sects}"
            )

        print(f"  ✅ All {len(valid_names)} expected components are valid.")

        out      = NEXTJS_DIR
        app      = os.path.join(out, "app")
        comp_dir = os.path.join(app, "components")
        public_assets = os.path.join(out, "public", "assets")

        # ── 1. Scaffold static files ──────────────────────────────────────
        _write(os.path.join(out, "package.json"),   PACKAGE_JSON)
        _write(os.path.join(out, "tsconfig.json"),  TSCONFIG_JSON)
        _write(os.path.join(out, "next.config.js"), NEXT_CONFIG)
        _write(os.path.join(out, "README.md"),      README_MD)
        print("📁 Scaffolded Next.js boilerplate")

        # ── 2. globals.css ────────────────────────────────────────────────
        globals_css_content = (
            "/* Auto-generated globals — fonts, variables, resets */\n\n"
            + (global_css or "")
        )
        _write(os.path.join(app, "globals.css"), globals_css_content)
        print(f"🎨 globals.css written ({len(globals_css_content)} chars)")

        # ── 3. layout.tsx ─────────────────────────────────────────────────
        safe_title = page_title.replace("'", "\\'")
        layout_content = LAYOUT_TSX.format(title=safe_title)
        _write(os.path.join(app, "layout.tsx"), layout_content)

        # ── 4. Write each component ────────────────────────────────────────
        # Preserve section order from the sections list
        ordered_names = [s["name"] for s in sections] if sections else list(components.keys())

        Path(comp_dir).mkdir(parents=True, exist_ok=True)

        written: list[str] = []
        for name in ordered_names:
            tsx = components.get(name)
            if not tsx:
                # This shouldn't happen — caught by validate_components above
                print(f"  ⚠️  No TSX for '{name}' — skipping (should have been caught earlier)")
                continue

            # Final asset-path normalisation (issue #7)
            tsx = _fix_asset_paths(tsx)

            # Re-validate after path rewriting (catch any edge cases)
            ok, reason = validate_tsx(name, tsx)
            if not ok:
                return {
                    "error": (
                        f"assembler_node: '{name}' failed post-rewrite validation: {reason}"
                    ),
                    "logs": [f"Post-rewrite validation failed for '{name}': {reason}"],
                }

            cname    = _component_name(name)
            filepath = os.path.join(comp_dir, f"{cname}.tsx")
            _write(filepath, tsx)
            written.append(name)
            print(f"  ✅ components/{cname}.tsx  ({len(tsx)} chars)")

        # ── 5. page.tsx ───────────────────────────────────────────────────
        page_tsx = _build_page_tsx(written)
        _write(os.path.join(app, "page.tsx"), page_tsx)
        print(f"📄 page.tsx written ({len(written)} components imported)")

        # ── 6. Verify page.tsx imports (issue #10) ────────────────────────
        abs_out = os.path.abspath(out)
        all_present, missing_imports = verify_page_imports(abs_out, written)
        if not all_present:
            return {
                "error": (
                    f"assembler_node: page.tsx is missing imports for: {missing_imports}"
                ),
                "logs": [f"page.tsx import verification failed: {missing_imports}"],
            }
        print(f"  ✅ page.tsx import verification passed.")

        # ── 7. Copy assets to public/assets/ ─────────────────────────────
        copied = 0
        if os.path.isdir(ASSETS_SRC):
            if os.path.exists(public_assets):
                shutil.rmtree(public_assets)
            shutil.copytree(ASSETS_SRC, public_assets)
            for _, _, files in os.walk(public_assets):
                copied += len(files)
            print(f"📦 Copied {copied} assets → public/assets/  (images/, videos/, posters/)")
        else:
            print("⚠️  No assets dir found — skipping asset copy")

        # ── 8. Final summary ──────────────────────────────────────────────
        print(f"\n✅ Next.js project ready at: ./{out}/")
        print(f"   Run:  cd {out} && npm install && npm run dev\n")

        # Issue #5: always return absolute path
        return {
            "nextjs_output_dir": abs_out,
            "logs": [
                f"Assembler: Next.js project written to {out}/",
                f"Components: {written}",
                f"Assets copied: {copied}",
            ],
        }

    except Exception as e:
        print(f"❌ Assembler node failed: {e}")
        return {
            "error": str(e),
            "logs":  [f"Assembler node failed: {e}"],
        }